import os, sys
os.system("pkg install pip")
os.system("pip install telethon")
os.system("pip install asyncio")
os.system("pip install datetime")
os.system("pip install dotenv")
os.system("pip install backend")
os.system("pip install python3")
os.system("pip install pyrogram")
os.system("pip install --upgrade pip setuptools")
os.system("pip install -r Requirements.txt")
os.system("clear")
os.system("sleep 5")
os.system("clear")
